FROM ubuntu:16.04
MAINTAINER Tim Hawes tim@easyfreeunix.com

RUN apt-get update
RUN apt-get -y install build-essential libboost-program-options-dev libsword-dev libreadline-dev cmake git
VOLUME /usr/share/sword/modules
VOLUME /usr/local/src
